ALTER TABLE clinics ADD COLUMN IF NOT EXISTS version INT DEFAULT 0 NOT NULL;
ALTER TABLE addresses ADD COLUMN IF NOT EXISTS version INT DEFAULT 0 NOT NULL;
ALTER TABLE contact_info ADD COLUMN IF NOT EXISTS version INT DEFAULT 0 NOT NULL;
ALTER TABLE business_hours ADD COLUMN IF NOT EXISTS version INT DEFAULT 0 NOT NULL;
ALTER TABLE holidays ADD COLUMN IF NOT EXISTS version INT DEFAULT 0 NOT NULL;
ALTER TABLE outbox ADD COLUMN IF NOT EXISTS version INT DEFAULT 0 NOT NULL;