package org.mdental.commons.constants;

/**
 * Constants for HTTP headers used across MDental services
 */
public final class MdentalHeaders {
    private MdentalHeaders() {
        // Prevent instantiation
    }

    /** Header for the authenticated user's username */
    public static final String USER_USERNAME = "X-User-Username";

    /** Header for the authenticated user's subject (ID) */
    public static final String USER_SUBJECT = "X-User-Subject";

    /** Header for the authenticated user's email */
    public static final String USER_EMAIL = "X-User-Email";

    /** Header for the authenticated user's clinic ID */
    public static final String USER_CLINIC_ID = "X-User-ClinicId";

    /** Header for the authenticated user's issuer (Keycloak realm) */
    public static final String USER_ISSUER = "X-User-Issuer";

    /** Header for request ID generated by the gateway */
    public static final String GATEWAY_REQUEST_ID = "X-Gateway-Request-Id";
}