# docker-compose.yml for local development
version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: mdental-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mdental-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: mdental-keycloak
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    ports:
      - "8080:8080"
    command: start-dev --import-realm
    volumes:
      - ./infrastructure/keycloak:/opt/keycloak/data/import
    networks:
      - mdental-network

  auth-core:
    depends_on:
      - postgres
      - keycloak
    build:
      context: ./
      dockerfile: core-services/auth-core/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mdental_auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KEYCLOAK_ADMIN_URL: http://keycloak:8080/admin/realms
      KEYCLOAK_AUTH_URL: http://keycloak:8080/realms/master/protocol/openid-connect/token
      KEYCLOAK_REALM_TEMPLATE_PATH: /opt/mdental/keycloak/realm-template.json
      KC_ADMIN_USER: admin
      KC_ADMIN_PWD: admin
      MDENTAL_AUTH_ALLOWED_ISSUER_PATTERNS: http://keycloak:8080/realms/platform,http://keycloak:8080/realms/mdental-
      INTERNAL_API_TOKEN: shared-secret-token-for-dev
    volumes:
      - ./infrastructure/keycloak:/opt/mdental/keycloak
    networks:
      - mdental-network

  clinic-core:
    depends_on:
      - postgres
      - keycloak
      - auth-core
    build:
      context: ./
      dockerfile: core-services/clinic-core/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mdental_clinic
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MDENTAL_AUTH_ALLOWED_ISSUER_PATTERNS: http://keycloak:8080/realms/platform,http://keycloak:8080/realms/mdental-
      AUTH_CORE_URL: http://auth-core:8081
      INTERNAL_API_TOKEN: shared-secret-token-for-dev
    networks:
      - mdental-network

networks:
  mdental-network:

volumes:
  postgres-data: