# MDental Platform Launcher Configuration
# Generated on Thu May 22 03:34:55 AM CEST 2025

# PostgreSQL
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres

# Keycloak
KEYCLOAK_PORT=9080
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=admin

# Services
SERVICE=discovery-server:8761
SERVICE=gateway-core:8080
SERVICE=auth-core:8081
SERVICE=clinic-core:8082
SERVICE=patient-core:8083
