spring.profiles.active=prod

# Prod: Load-balanced service URIs with circuit breakers
spring.cloud.gateway.routes[0].id=clinic-core
spring.cloud.gateway.routes[0].uri=lb://clinic-core
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/clinics/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/clinics/(?<cid>[^/]+)(?<segment>/.*), /api/clinics/${cid}${segment}
spring.cloud.gateway.routes[0].filters[1]=AddRequestHeader=X-Gateway-Request-Id, ${java.util.UUID.randomUUID()}
spring.cloud.gateway.routes[0].filters[2]=name=CircuitBreaker, args=name:clinicServiceCircuitBreaker,fallbackUri:forward:/fallback/clinic

spring.cloud.gateway.routes[1].id=patient-core
spring.cloud.gateway.routes[1].uri=lb://patient-core
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/clinics/*/patients/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/clinics/(?<cid>[^/]+)/patients(?<segment>/.*), /api/clinics/${cid}/patients${segment}
spring.cloud.gateway.routes[1].filters[1]=AddRequestHeader=X-Gateway-Request-Id, ${java.util.UUID.randomUUID()}
spring.cloud.gateway.routes[1].filters[2]=name=CircuitBreaker, args=name:patientServiceCircuitBreaker,fallbackUri:forward:/fallback/patient

spring.cloud.gateway.routes[2].id=appointment-core
spring.cloud.gateway.routes[2].uri=lb://appointment-core
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/clinics/*/patients/*/appointments/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/clinics/(?<cid>[^/]+)/patients/(?<pid>[^/]+)/appointments(?<segment>/.*), /api/clinics/${cid}/patients/${pid}/appointments${segment}
spring.cloud.gateway.routes[2].filters[1]=AddRequestHeader=X-Gateway-Request-Id, ${java.util.UUID.randomUUID()}
spring.cloud.gateway.routes[2].filters[2]=name=CircuitBreaker, args=name:appointmentServiceCircuitBreaker,fallbackUri:forward:/fallback/appointment

spring.cloud.gateway.routes[3].id=auth-core
spring.cloud.gateway.routes[3].uri=lb://auth-core
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/auth/(?<segment>.*), /${segment}
spring.cloud.gateway.routes[3].filters[1]=AddRequestHeader=X-Gateway-Request-Id, ${java.util.UUID.randomUUID()}
spring.cloud.gateway.routes[3].filters[2]=name=CircuitBreaker, args=name:authServiceCircuitBreaker,fallbackUri:forward:/fallback/auth

# Allow your Keycloak issuer URI as a valid Mdental-Security issuer
mdental.auth.allowedIssuerPatterns[0]=${spring.security.oauth2.resourceserver.jwt.issuer-uri}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=\
  http://localhost:9080/realms/platform/protocol/openid-connect/certs

spring.main.web-application-type=reactive
